spring:
  main:
    banner-mode: off
  application:
    name: gastarmenos
  server:
    port: ${SERVER_PORT:8080}

  datasource:
    url: jdbc:postgresql://localhost:5432/gastarmenos
    username: app_gastar_menos
    password: app_gastar_menos
    driver-class-name: org.postgresql.Driver

  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    schemas: public
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
        springframework:
          web: DEBUG
      com:
        montebruni:
          gastarmenos: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui.html